### ISSUE TITLE
Unable to Commit - Fails with Java stackmap frame error

### ISSUE THREAD

**Issue by mjwoodsphx** [SmartBear/ready-git-plugin#14]
While attempting to commit (Save and Share) an error is generated in the error file.  The error is below.  I am able to perform an Update From Repo (even though the repo is empty) without any issues, indicating communication to the server seems to be in order.

I am hoping that someone can help me with this error.  I have researched it and tried adding lines to the ReadyAPI-1.9.0.vmoptions file for -XX:-UseSplitVerifier and -noverify with no luck.

Thank You,

Michael Woods Denwood
American Airlines

Exception in thread "JavaFX Application Thread" java.lang.VerifyError: Expecting a stackmap frame at branch target 12
Exception Details:
  Location:
    javafx/application/Application.<init>()V @0: ldc
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 12a2 12a4 01b8 00aa 57a7 0004 572a b700
    0x0000010: 882a 01b5 007f b1                      
  Exception Handler Table:
    bci [0, 9] => handler: 12

	at javafx.scene.control.Control.<clinit>(Control.java:86)
	at com.sun.javafx.webkit.theme.ScrollBarThemeImpl$1.invalidated(ScrollBarThemeImpl.java:109)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
	at javafx.scene.web.WebEngine.setView(WebEngine.java:994)
	at javafx.scene.web.WebView.<init>(WebView.java:274)
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent$WebViewInitialization.run(EnabledWebViewBasedBrowserComponent.java:436)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent.getWebEngine(EnabledWebViewBasedBrowserComponent.java:266)
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent.access$6(EnabledWebViewBasedBrowserComponent.java:265)
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent$4.run(EnabledWebViewBasedBrowserComponent.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent.getWebEngine(EnabledWebViewBasedBrowserComponent.java:266)
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent.access$6(EnabledWebViewBasedBrowserComponent.java:265)
	at com.eviware.soapui.support.components.EnabledWebViewBasedBrowserComponent$4.run(EnabledWebViewBasedBrowserComponent.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
..... with the same error repeated over and over.

**Comment by prakashmrec** [comment]
The exception trace doesn't seem to be related to commit operation. Can you please add a system property **"soapui.browser.disabled=true"** and try again? The exception trace is related to browser component initialization and if you disable browser then browser component will not be intialized. Browser component is not required for git integration.
